### ISSUE TITLE
Single-threaded `talc` usage

### ISSUE THREAD

**Issue by ratankaliani** [SFBdragon/talc#21]
I'm currently trying to compile Rust code with dynamic memory allocation to a Rust target that doesn't have access to atomic's and so I can't use `spin`.

Does this look like the right approach for initializing a single-threaded `global_allocator` for dynamic memory in my `main` file that wouldn't make use of Atomic's?

```rust
#[global_allocator]
static ALLOCATOR: Talck<talc::AssumeUnlockable, ErrOnOom> =
    unsafe { Talc::new(ErrOnOom).lock_assume_single_threaded() };
```

**Comment by SFBdragon** [comment]
Unless I'm overlooking something, this looks exactly right. I'll close this, but leave a reply if you're encountering any problems with this setup.

(I'm weighing up how I document this use case in #19 so thanks for reaching out. I'll try to make this more clear in the next version along with documentation improvements in #20 as well)
