### ISSUE TITLE
Unaligned read of Tag

### ISSUE THREAD

**Issue by shamatar** [SFBdragon/talc#27]
Not sure if I can give a short example to reproduce, but on the architecture without fast unaligned reads the line https://github.com/SFBdragon/talc/blob/618d505de6d561680f426a89896fc6d90c585aa7/src/talc.rs#L101 will trigger an exception. From what I tried it was always 0x3 in the low bits, while alignment of Tag itself is usize (4 on my setup).

**Comment by shamatar** [comment]
If one fixes the line above by writing individual bytes to `*mut u8` without cast, then the next error happens at https://github.com/SFBdragon/talc/blob/618d505de6d561680f426a89896fc6d90c585aa7/src/talc.rs#L303 writes

**Comment by SFBdragon** [comment]
I can only speculate on why this is happening as unaligned reads should never occur. If there's a bug in the allocator, it might be buried quite far from `fn tag_from_alloc_ptr`.

1. What architecture is this exactly? Other system details could be useful.
2. Is the code for the project publicly accessible?

Talc isn't tested as heavily on 32 bit architectures. WASM/MIRI tests do cover it, but perhaps I just need to get QEMU running and fuzz the allocator on it and see what happens. Getting the exact arch for this would be best though.

Would it be possible for you to clone the project and run the following command on this machine from the project root?
`RUST_BACKTRACE=full cargo fuzz run fuzz_talc`
This'll only work if you have a hosted system with `std` and cargo-fuzz installed: `cargo install cargo-fuzz`
If you get an error dump, it'll suggest running `cargo fuzz tmin ...` which would be helpful information too.

This would help narrow down the possibilities a lot.

**Comment by shamatar** [comment]
I'll try to make an example if I do not figure out the reason why tag ends up at such offsets. Presumably there is no logical reason to have Tag located at such offsets,maybe some tagging/meta information bits were not masked at some point. I didn't get through the code base yet to understand memory layout.

The architecture is riscv32 bare metal, without fast unaligned access support, so unaligned store of double-word triggers an exception that is unhandled by default

**Comment by SFBdragon** [comment]
Fair enough. Happy to see RISC-V getting some love, I have a soft spot for it.

Note that the `tag_or_tag_ptr` is expected to be either a tag (base pointer with the low 2 bits being metadata, usually set). Or a pointer to the tag above it (should always be 4 byte aligned on 32 bit systems).

Here's some ideas of what might have gone wrong:
- a calculation of a base pointer went horribly wrong and it ended up above the chunk, making a tag look like a pointer
- the data at post_alloc_ptr got overwritten somehow
- the calculation of the post_alloc_ptr went awry

Here's what an allocated chunk looks like:
`prev chunk | [gap] data data data data, tag | next chunk`
Or
`prev chunk | [gap] data data data data, tag_ptr, [gap], tag | next chunk`
The location of tag and tag_ptr should all be usize-sized and usize-aligned. Chunk borders are also usize-aligned.

The following ordering invariants should hold
tag & ~3 <= allocation ptr
tag_ptr > post_alloc_ptr
post_alloc_ptr > allocation_ptr

If you could dump some of this data and upload it here, I'll see if I can make heads or tails of it.

**Comment by shamatar** [comment]
I'll investigate a case of accidental overwriting first, thank you for details

**Comment by shamatar** [comment]
Ok, long story short it was indeed unintended overwriting - there was a custom Drop on one of the allocating data types that contained a shortcut branch, but was missing `return` in the body of that branch. I'll close it as it was specific interplay with outer code

**Comment by SFBdragon** [comment]
Neat, glad it's sorted :)
