### ISSUE TITLE
Possible to provide approximate usage metrics?

### ISSUE THREAD

**Issue by wyager** [SFBdragon/talc#29]
First, thanks for creating this. It seems like a very tidy solution for a no_std arena allocator and has been working well for me so far. 

One thing I would like to do with the project I'm working on is get an idea of how much memory is left for allocation. Obviously this can only give an approximate indication, what with heap fragmentation and so on, but is there any reasonably straightforward way to expose something like `bytes_used() -> usize` and/or `bytes_available() -> usize`?

**Comment by SFBdragon** [comment]
I should probably document this a bit more obviously in the README.

> [Features] "counters": Talc will track heap and allocation metrics. Use Talc::get_counters to access them.

This'll return a struct that contains both these stats and more. (This feature is a relatively recent addition so feedback is especially welcome.)

I'll close this for now though.
