### ISSUE TITLE
Add convenience function to cut a hole in a Span returning two new Spans

### ISSUE THREAD

**Issue by bjorn3** [SFBdragon/talc#31]
The memory map contained in device trees includes the memory range that contains the kernel. As such I have to cut out this memory range from each memory map entry. It would be nice if talc has a builtin function for this. That would allow something like the following assuming `cut_out` is the name of this function:

```rust
let kernel_image: Span = todo!();
for region in device_tree.memory().regions() {
    let region_span = Span::from_base_size(region.starting_address as *mut _, region.size.unwrap());
    if region_span.overlaps(kernel_image) {
        let (before, after) = region_span.cut_out(kernel_image);
        GLOBAL_ALLOC.lock().claim(before).unwrap();
        GLOBAL_ALLOC.lock().claim(after).unwrap();
    } else {
        GLOBAL_ALLOC.lock().claim(region_span).unwrap();
    }
}
```

**Comment by SFBdragon** [comment]
v4.4.1 is out with the `except` function:

```rust
let (before, after) = region_span.except(kernel_image);
```

And you should be good to go. Thanks for the suggestion!

**Comment by bjorn3** [comment]
Thanks! Using `except` as name is fine.
