### ISSUE TITLE
Docs: Shouldn't `ARENA` bytes be aligned?

### ISSUE THREAD

**Issue by overlookmotel** [SFBdragon/talc#35]
Example in README for using `talc` as global allocator:

```rs
use talc::*;

static mut ARENA: [u8; 10000] = [0; 10000];

#[global_allocator]
static ALLOCATOR: Talck<spin::Mutex<()>, ClaimOnOom> = Talc::new(unsafe {
    ClaimOnOom::new(Span::from_const_array(core::ptr::addr_of!(ARENA)))
}).lock();
```

Would it not be advisable to ensure `ARENA` has a higher alignment than 1? e.g.:

```rs
const ARENA_SIZE: usize = 10000;

// `align(128)` to specify alignment.
// `C` to ensure array itself is aligned if layout randomization enabled.
#[repr(C, align(128))]
struct AlignedBytes([u8; ARENA_SIZE]);

static mut ARENA: AlignedBytes = AlignedBytes([0; ARENA_SIZE]);

#[global_allocator]
static ALLOCATOR: Talck<spin::Mutex<()>, ClaimOnOom> = Talc::new(unsafe {
    ClaimOnOom::new(Span::from_const_array(core::ptr::addr_of!(ARENA.0))) // <-- ARENA.0
}).lock();
```

Perhaps if `ARENA` is large enough, we can rely on it being aligned anyway, but maybe it's better to be explicit?

**Comment by SFBdragon** [comment]
Hi, talc does whatever it needs to do internally to ensure it's own metadata and the allocations it makes are sufficiently aligned.

If you try to `claim` a poorly aligned Span, and check the returned Span, you should see that the resulting Span is a well-aligned subspan of the original Span. (Same goes for other arena-modifying functions, they all ensure that the allocation routines have strong guarantees about alignment.) So aligning your arena might save a few bytes, but it shouldn't be a major concern.

Talc makes no guarantees about how it aligns things. Currently it's to the system word size but I have plans to increase that alignment a bit in a future version. (So don't rely on it, I may break it ^_^)

Closing this for now. Feel free to follow up if you have further questions.

**Comment by overlookmotel** [comment]
Thanks loads for coming back and clarifying. My suggested change is unnecessary. Great!

**Comment by SFBdragon** [comment]
No problem! In fact I don't believe I've explicitly clarified this anywhere in the documentation, so that's probably worth amending at some point - it's a reasonable concern given how certain doc comments are worded.
